"""add_exercise_tables_and_relationships

Revision ID: 02d81a4ba5c8
Revises: c3849ef5c8cd
Create Date: 2025-04-13 22:29:38.047832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d81a4ba5c8'
down_revision: Union[str, None] = 'c3849ef5c8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('emg_data', sa.Column('exercise_set_id', sa.UUID(), nullable=True))
    op.drop_index('emg_data_time_idx', table_name='emg_data')
    op.create_foreign_key(None, 'emg_data', 'exercise_sets', ['exercise_set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emg_data', type_='foreignkey')
    op.create_index('emg_data_time_idx', 'emg_data', [sa.text('time DESC')], unique=False)
    op.drop_column('emg_data', 'exercise_set_id')
    op.drop_table('exercise_sets')
    op.drop_table('exercises')
    # ### end Alembic commands ###
