"""create sensors table and emg data hypertable

Revision ID: c3849ef5c8cd
Revises: ae886fe2c5f1
Create Date: 2025-02-25 15:39:56.780459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3849ef5c8cd'
down_revision: Union[str, None] = 'ae886fe2c5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emg_data',
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('sensor_position', sa.Enum('left_bicep', 'left_forearm', 'right_bicep', 'right_forearm', name='sensor_position_enum', native_enum=False, create_constraint=True), nullable=False, comment='Allowed values: left_bicep, left_forearm, right_bicep, right_forearm'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('time', 'sensor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emg_data')
    op.drop_table('sensors')
    # ### end Alembic commands ###
